* Tofu
** From Rhys
You always want to use Firm or Extra Firm. Extra Firm is used in at least 90% of all tofu cooking. 9% is Firm. 1% is other like Silken or Soft

I love soft in ramen and noodle soups. But it has very limited application.

Extra Firm will get you the most mileage.

If you have firm, the simplest thing to do is press the tofu for 5-20 minutes to get out the water

Then cube it and let it simmer until it warms through after you have made the curry

No real cooking required in this simplest of all worlds

Press, cube, add towards the end.

However you can do better.

Extra firm can be pan fried until brown in slabs. You cut the block into thirds longwise (thick sheets) and then pan fry in shallow oil until golden brown

You MUST press the tofu

Then you cube up the fried slabs.

But you can do better.

Extra Firm tofu:
1) press for 10 minutes
2) cube
3) combine 1/4 cup flour and 1/4 cup corn starch in a bowl. Some salt and pepper too if you want.
4) toss the cubes
5) deep fry until crispy chicken nuggets

(Wok of oil or a pan of oil - submerged works best or you spend your life fucking around flipping cubes)

Take these beautiful crispy cubes of fried goodness (salt super optional) and add them to the curry bowls after plating.

The battered and fried cubes will stand up to a curry liquid but it is most fun if you just add it at the end so they don’t get totally soaked

If you do not press the liquid out of the tofu, the nuggets will explode when you deep fry them because the water is trapped in the batter shell. It sucks. Don’t do that.

So put the tofu between two plates and throw some bags of beans or soup cans or a heavy pot on it and let it sit and press for 10 minutes.

Also the flour corn starch combo…you can totally just use pure corn starch.

After years of doing it, here is the best way: dump a 1/2 cup of corn starch into a 1 gallon zip lock bag. Throw in the cubes. Seal. Shake shake shake shake.

And finally, if you have the time, the ultimate preparation of fried tofu:
1) completely freeze one block of extra firm tofu in its packaging.
2) completely thaw said tofu in its packaging.
3) optionally repeat steps 1 and 2 for a second freeze and thaw
4) press the result
5) cube and fry

The texture will be like a fried pork rind when you cook it

If you don’t fry it, this preparation of the tofu will absorb massive amounts of the cooking liquid and become super juicy and tasty

So fry for crispy goodness or don’t fry for juicy goodness

Soft and Silken tofus cannot be pressed and release no liquid. They are essentially a firm custard.

If you scoop it out into a bowl and put maple syrup on it, you have flan. Serious. No cooking. Just put syrup on it cold. Flan.
