** Resources
- [[https://swappa.com][Swappa]]
- [[https://support.apple.com/guide/assistive-access-iphone/set-up-assistive-access-devcd5016d31/ios][Assistive Access User Guide for iPhone]]
- [[https://www.apple.com/apple-watch-for-your-kids/][Apple Watch For Your Kids]]


** iPhone Buying Thread
corvino
  Today at 6:20 AM
iPhone buying help. I’m trying to get a cheap but new-ish iPhone for my 12 year old, and since I haven’t been in the market for an upgrade for a while I’m totally out of the loop on what to get and too tired to do the research.
I mostly want him do be able to text, use maps, call/facetime, and use Strava on his Apple Watch. It would actually be great if it didn’t do games or social media (hey, parental controls, I’m looking at you).
It looks 16e is cheaper than 15? Any bargains or deals out there?
I’ll start a thread.
Thanks!
18 replies


corvino
  Today at 6:20 AM
Recs and info here. Thanks!


jsorge
  Today at 7:01 AM
I’d consider looking around for a refurb too. I think Amazon supposedly has a good selection. You could probably get a deal on a 13 or 14 which sounds like matches the requirement profile.


Jeff
  Today at 7:09 AM
I know you’re going to just think this is me trying to pad out my retirement fund, but hear me out: buy a refurbished 16e or 16-something.
The 16s are the best phone Apple builds today and will last for five to six years. If you want to the next time you buy your child a phone it can be as a graduation present.


corvino
  Today at 7:11 AM
How many kids do you think I have?!


Jeff
  Today at 7:20 AM
Don’t know, but the advice actually still stands. If your 12yo is the oldest, buy the 16-ish now for them. When the next child is ready for a phone hand down the 16-ish and upgrade the previous 12yo. (Assuming age has privileges.)
This advice is valid for 1-3 kids. If you have four to a dozen kids, I’m kinda lost.


corvino
  Today at 7:22 AM
I was joking about the padding your retirement account. :joy:
7:23
The argument against advice is that he is bound to loose it writhing a year, but I can process that privately. (I guess I chose not to.) :wink:
:joy:
1



jack
  Today at 8:58 AM
Check out swappa.com. I bought a couple of phones there for my family, and some for testing too.
:this:
1



sfaxon
  Today at 9:12 AM
I have a friends & family discount you can use. I think it’s 15% off from Apple.


Jeff
  Today at 12:21 PM
Yeah. The losing it part is a thing. I always pay for Apple Care on my phones. So that might help.


emarley
:dark_sunglasses:  Today at 1:29 PM
Are there still two tiers of Apple Care? (Yes, phones and Apple Care help fund my retirement too.)
1:31
16e is interesting to some because it uses the first cellular modem designed by Apple. Not sure that’s a pro or con in your case, but helps explain why there’s a mid-year model with a new naming pattern? (edited) 
1:34
For your case it might be enough to set him up with a cellular Apple Watch (without a phone). Or a cellular Apple Watch plus a cheaper iPhone that mostly lives in a drawer at home.
1:35
Then there’s almost no way to play games, but it can still track workouts, call home, and even text via transcription.
1:36
https://www.apple.com/apple-watch-for-your-kids/
AppleApple
Apple Watch For Your Kids
Use your iPhone to manage watches for the whole family — even if the kids don’t have an iPhone yet. It’s independence for them, peace of mind for you. (90 kB)
https://www.apple.com/apple-watch-for-your-kids/



sfaxon
  Today at 1:37 PM
I’ve considered this for when our kids get older https://support.apple.com/guide/assistive-access-iphone/set-up-assistive-access-devcd5016d31/ios
Apple SupportApple Support
Set up Assistive Access on iPhone
Set up Assistive Access for a family member or someone you care for and customize it so that iPhone works best for them.


corvino
  Today at 2:05 PM
That’s good thoughts. He has a watch, but it’s not that great for communicating with his friends. And I want to leave at pools and fields and somehow I feel the phone would work a little better. I also want him to arrange more of his social/practice stuff, and have access to his calendar including the soccer feed.
Also, you can’t get Strava without a phone. He is running, both for XC/track and soccer, and he wants to track his metrics in all that.
We’ll see how it turns out. T-mobile gave me a fee line. My sister said “you can regret it like all the friends I know who’ve done it.”
2:06
I may have missed that you are at Apple now, 
@sfaxon
. Congrats!
