* [[https://www.pugetsoundsailing.com][Puget Sound Sailing Institute]]
22307 Dock Avenue, Des Moines, WA 98198
* [[http://www.washingtonyachtclub.org][Washington Yacht Club]]
** [[http://www.washingtonyachtclub.org/guide-intro][Guide]]
** [[http://www.washingtonyachtclub.org/lessons][Lessons]]
*** Novice
**** DH Novice
No prerequisites. We will learn to sail Flying Juniors which are a
double handed boats (two-person). Please read through the Sailing Guide,
available on the website under How to Sail tab.
**** SH Novice - Bravo
This class covers the basics of sailing using our Bravo fleet. The Bravo
is a simple, novice-friendly singlehanded (i.e. sailed by one person)
boat. You'll learn the fundamentals of sailing, how to rig the boat,
and, most importantly, spend time sailing! The singlehanded rating also
opens the door to the more challenging (and faster) Laser
**** SH Laser Novice
Prerequisite of Bravo or DH Novice class completion required. We will
learn to rig and sail Lasers. Note that you MUST have a Bravo or DH
rating to join this class.
*** Advanced
**** Catamaran Novice
Learn to rig and sail our catamarans, a step up in both challenge and
speed from our novice dinghies. Either one intermediate or both novice
ratings are required.
**** Dinghy Racing Fundamentals
Are you excited about sailing and want to take your sailing experience
to the next level? Have you ever watched a sailboat race and felt lost
and confused? Do you have an FJ or Laser novice rating? If you answered
yes to all of these questions, then this intro to racing course is
perfect for you! In this weekly course, we will go over the racing rules
and how to use them, strategies for racing starts, and upwind/downwind
racing tactics. Depending on interest and feedback, we will schedule
this course as a weekly clinic or as a continuous course that meets
every Monday. No racing experience necessary. SH or DH novice rating
required. This is a new course. If you enroll, please email the
instructor to describe what you hope to learn from the course and all
relevant sailing/racing experience.
**** Beyond Novice
This is a weekly clinic for sailors to learn about and practice more
advanced techniques than they did in their novice classes. It's somewhat
less formal than those, with the subjects from week to week depending on
the instructor, the students, and the conditions that day.
*** Specialty
**** Keelboat Clinic
IF YOU SIGN UP FOR THIS, make sure you are subscribed to the WYC_INFO
mailing list; This is an informal weekly gathering in which we take out
our keelboats for cruises on the lake. If you want to get involved in
sailing them, this is a great place to start. What exactly is covered
each week depends on the students, the skippers, and the
conditions. It's well suited to sailors of all skill levels. If you sign
up, you don't need to come every time. Please respond to the class
announcements to let the instructors know whether you will be attending
week by week.
**** Daysailers
This class will teach sailing on the club's two Ensigns, J22 and Flying
Scott. SH or DH novice rating is a prerequisite.
**** Introduction to Windsurfing
Introduction to Windsurfing. A SH or DH Novice rating or previous
Sailboard experience REQUIRED to enroll.
