* Nicole
Thanks Nicole!

We're definitely going to make some tweaks. I've emailed Jeanne, and started refining our work list that we use. Currently hasn't been updated enough from two years ago, so we'll capture the improvements in that as we go.

I think the biggest single thing is going to be moving up the first pizza order and volunteer arrival time fifteen minutes. Both were late today by a few minutes, which I think we should anticipate, but even starting at 11:15 where I had the order I think the time is too tight. I think if K-2 had been entirely ready at 11:25, we would not have felt less of that pace. (Although I don't know that we've ever had that many classes arrive around the same time before.) And to your point on assigning work, I think it will be easier to have fewer people do K-2 then more people split into smaller grade groups. But it needs to get done earlier.

Once we have the 11:25 prep dialed in, the rest of the day should be easy.

One thing I was thinking might be helpful is getting a few of the thermal pizza-box bags for the WFA. It would help keep the pizza warm, but that's really secondary to the help organizing the classes. This order was really big, and the order alone took up a ton of counter space. Then we could group each class in a bag, and potentially stack the two classes for each grade. I think we'd only need a few, as once we free a Pizza Gallery bag or two we can start using theirs. It looks like you can get them pretty cheap. What do people think of that?

I definitely want to do something with signs. I'm thinking color would be really helpful. So each grade would have a color family, and each class a shade of that color family. So Kindergarten might be two shades of green. Those colors could be both on the order sheets and the sign. The sign can mark the spot where the grade is going to go until the pizza is boxed, and then it can identify the teacher. If we are using thermal bags to store each class's pizza, potentially it can slip into a label holder on the bag (I think they have these).

Unless I'm forced away from it, I'm going to do labels again next time. I'm going to do them on bigger labels, and get them on plates the day before. Then plates will be organized by class when we start putting everything together. I was a bit surprised that labels weren't faster; both peeling them off the sheet and separating plates was a little tricky.

Apples are definitely a work in progress. We used to be able to get them reliably at Costco, but so far that hasn't worked this year. I bought everything WinCo had (20 12 oz bags at $1.50/bag). I think we were too generous handing out apple slices, so I'm not sure what would have happened if we were more careful. But you can easily pay 2-4x that for apple slices, and still not be able to get enough at each store. I am going to get a handle on how many slices we go through for each kid receiving pizza, assuming that relationship will be fairly steady. (I think we currently have 309 kids ordering, so that can be a lot of slices ...) I'm definitely open to ideas and info here. It would be great if Costco starts being more reliable for Apples, or find another wholesaler within a similar distance. Dorothy keeps cautioning against trying to slice our own apples, but I have that in the back of my mind; I'm going to get prices from Cash & Carry next time I go.
