LN1 skills drills and games suggestions for Week 4 JNP, 2021

Stake out a spot on flat ground as soon as possible.  Maybe go out BEFORE JNP Starts and stake it with cones.  If your group is small, 5-6 kids, you can team up with another small group.  Sometimes games are more fun with more kids…

COVID Reminders:  Always good at beginning of a game to remind them no touching, stay 2 skis distance apart.

Possible warm-up:  T-Rex Hokey Pokey, everyone standing in a circle, first without skis, then with skis ON.  (same as regular Hokey Pokey, just make it dinosaur-themed, so instead of hands, legs, head, say claws, big snout, sharp teeth, tail, etc)

* GAME:  Silly Walks Circle (low intensity)

SKILL: 1 ski balance
SUPPLIES:  No poles for this game.  No Skis first time through, then on skis (may need to make circle larger once everyone has skis on).

Standing in a circle facing each other:  Do the following in order, each one for 30 seconds or until everyone has got the idea.
- March in place, raising knees high
- March in place, raising knees high, swinging arms (make sure everyone’s alternate.  No camel walking or A-Framing)
- Tiny skip (2 little hops on same foot), no arms
- Tiny skip, add arms  -- once everyone has got this…
- Add some power to the skips and arms, still standing in place in circle.
- Then, staying in a circle format, have everyone follow you, and skip around in a circle, moving arms rhythmically.  A song would be perfect for this…!  Row, Row, Row Your Boat, first time thru, then change Row, Row to ‘Move, Move, Move your Skis, Gently In a Circle, Merrily, Merrily, Merrily, Merrily, life is but a smirkle’ (or some other silly nonsense word),  let kids help you invent verses…

* GAME:  What time is it, Rexy (T-Rex)?
https://xcskination.com/courses/what-time-is-it-mr-wolf/

SKILL:  This is good practice for starting, stopping, turning, edging, forward balance.
SUPPLIES:  1) Cones to mark game area.2) Noodles for the ‘it’ people to keep social distance.  3)Flat area, no tracks, 50 m square, if possible, or as large as you can find. 3) No poles.
Play in Flat area.

* GAME:  Dino Egg hunt:
https://xcskination.com/courses/easter-egg-hunt/

SKILL: Wedging, wedge control, stopping, starting on a hill.
SUPPLIES:  1) Several 15(?) Small balls or other small objects from the staff room, 2) two buckets to put balls in at the bottom  of the hill 3) cones to mark the finish line.
NOTE: This needs a very gentle hill for beginners. More advanced beginners can try a steeper hill.  Go one at a time to avoid collisions.  If the slope is wide enough can go two at a time in parallel.

* GAME:  Duck, Duck, GOOSE!
https://www.considerable.com/entertainment/games/duck-duck-goose/

SKILL: Edging inside of your ski.
SUPPLIES: 1 noodle for each player.  Stand in a circle on skis, 2 arms-length apart, NO POLES.
COVID MODIFICATION:  Each player has a noodle that they use to tag the other person.  Remind about no-touch tagging.
NOTE:  With young kids/new skiers play this game slowly first until everyone gets the idea.  Tell them that in order to get away from ‘IT’ they are going to have to dig in the edge of their ski to keep going around the circle.   Be sure everyone has a chance to be ‘IT’ and to REVERSE the direction so that everyone gets practice edging with both skis.
